# Generated by Django 3.2.3 on 2021-05-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_mu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='mu',
        ),
    ]
