# Generated by Django 3.2.3 on 2021-05-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_room_mu'),
    ]

    operations = [
        migrations.AddField(
            model_name='sounds',
            name='name',
            field=models.CharField(default='mda', max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(upload_to='background'),
        ),
        migrations.AlterField(
            model_name='sounds',
            name='music',
            field=models.FileField(upload_to='music'),
        ),
    ]
