# Generated by Django 3.2.3 on 2021-05-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210521_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sounds',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
